name: ci/cd pipeline

on:
    push:
        branches: [ main ]
            

jobs: 
    build-and-deploy: 
        runs-on: ubuntu-latest
        
        steps: 
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Node.js version
              uses: actions/setup-node@v1
              with:
                node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Build Docker image
              run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/container-tut:latest .  

            - name: Login to Docker Hub
              run: echo ${{secrets.DOCKERHUB_PASSWORD}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
              
            - name: Push image to Docker Hub
              run: docker push ${{secrets.DOCKERHUB_USERNAME}}/container-tut:latest
              
            - name: Done
              run : echo "Image has been pushed to Docker Hub"
              
            - name: Deploy to EC2 via SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{secrets.EC2_HOST}}
                  username: ${{secrets.EC2_USERNAME}}
                  key: ${{secrets.EC2_KEY}}
                  script: |
                      docker pull ${{secrets.DOCKERHUB_USERNAME}}/container-tut:latest
                      docker stop container-tut || true 
                      docker rm -f container-tut || true
                      docker run -d  --restart unless-stopped  --name container-tut  -p 8000:8000  ${{ secrets.DOCKERHUB_USERNAME }}/container-tut:latest  